// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvAKRiS5chRjjfULKdh_TTgb379imizRs',
    appId: '1:649725281538:web:2a973929c6ee0581872e1b',
    messagingSenderId: '649725281538',
    projectId: 'tesis-v2-9226e',
    authDomain: 'tesis-v2-9226e.firebaseapp.com',
    storageBucket: 'tesis-v2-9226e.firebasestorage.app',
    measurementId: 'G-4MH3ZMBPH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtky0myYpBoHKlpKO0tKXcGE8g5tUiEtA',
    appId: '1:649725281538:android:06705018ae00ba90872e1b',
    messagingSenderId: '649725281538',
    projectId: 'tesis-v2-9226e',
    storageBucket: 'tesis-v2-9226e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE2HqK88lUf1LEwlG0GtpwhzFrwGYXt90',
    appId: '1:649725281538:ios:9647fa0a53c0a4f0872e1b',
    messagingSenderId: '649725281538',
    projectId: 'tesis-v2-9226e',
    storageBucket: 'tesis-v2-9226e.firebasestorage.app',
    androidClientId: '649725281538-53st58bceg60ppobjdmd0dsa9tj132p0.apps.googleusercontent.com',
    iosBundleId: 'com.example.tesisV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE2HqK88lUf1LEwlG0GtpwhzFrwGYXt90',
    appId: '1:649725281538:ios:9647fa0a53c0a4f0872e1b',
    messagingSenderId: '649725281538',
    projectId: 'tesis-v2-9226e',
    storageBucket: 'tesis-v2-9226e.firebasestorage.app',
    androidClientId: '649725281538-53st58bceg60ppobjdmd0dsa9tj132p0.apps.googleusercontent.com',
    iosBundleId: 'com.example.tesisV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvAKRiS5chRjjfULKdh_TTgb379imizRs',
    appId: '1:649725281538:web:20a5d15d27ab9f2d872e1b',
    messagingSenderId: '649725281538',
    projectId: 'tesis-v2-9226e',
    authDomain: 'tesis-v2-9226e.firebaseapp.com',
    storageBucket: 'tesis-v2-9226e.firebasestorage.app',
    measurementId: 'G-E1C5FY41T2',
  );

}